# Generated by Django 3.1.12 on 2021-06-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productPrice', models.FloatField()),
                ('productName', models.CharField(max_length=255)),
                ('productDescription', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
