# Generated by Django 3.2.4 on 2021-06-13 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productName',
        ),
    ]
