# Generated by Django 3.2.4 on 2021-06-14 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_productname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
