# Generated by Django 3.2.4 on 2021-06-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Message',
            field=models.TextField(max_length=250),
        ),
    ]
