# Generated by Django 3.2.4 on 2021-06-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_checkout_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
