# Generated by Django 3.2.4 on 2021-06-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20210617_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='productName',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='productPrice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
