# Generated by Django 3.2.4 on 2021-06-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210614_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='awesome',
            field=models.BooleanField(default=False),
        ),
    ]
