# Generated by Django 3.2.4 on 2021-06-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='productName',
            new_name='S_Name',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='productPrice',
            new_name='S_Price',
        ),
        migrations.AddField(
            model_name='shop',
            name='S_Description',
            field=models.TextField(default='', max_length=250),
        ),
    ]
