# Generated by Django 3.2.4 on 2021-06-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210613_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='S_Description',
            field=models.TextField(max_length=250),
        ),
    ]
