# Generated by Django 3.2.4 on 2021-06-14 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shop_s_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
